
Before customDFS
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered !turnPoint
Entered customDFS
Entered turnPoint